# Generated by Django 4.2.2 on 2023-06-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descr', models.CharField(max_length=300)),
                ('img_path', models.CharField(max_length=300)),
            ],
        ),
    ]
