# Generated by Django 4.2.2 on 2023-06-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topanime', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='descr',
            new_name='DESCR',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='img_path',
            new_name='IMGPATH',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='title',
            new_name='TITLE',
        ),
        migrations.AddField(
            model_name='anime',
            name='SHOWN',
            field=models.BooleanField(default=False),
        ),
    ]
